### ISSUE TITLE
Update webview_flutter version to 4.0.1

### ISSUE THREAD

**Issue by tomk9** [prahack/vimeo_player#10]
`pubspec.yaml`
```yaml
dependencies:
  vimeo_player_flutter: ^0.0.3+2
  webview_flutter: ^4.0.1
```
```shell
flutter pub get
```
```
Because vimeo_player_flutter 0.0.3+2 depends on webview_flutter ^3.0.0 and no versions of vimeo_player_flutter match >0.0.3+2 <0.1.0, vimeo_player_flutter ^0.0.3+2 requires webview_flutter ^3.0.0.
So, because td_mobile_v2 depends on both vimeo_player_flutter ^0.0.3+2 and webview_flutter ^4.0.1, version solving failed.
Running "flutter pub get" in td_mobile_v2...                            
pub get failed (1; So, because td_mobile_v2 depends on both vimeo_player_flutter ^0.0.3+2 and webview_flutter ^4.0.1, version solving failed.)
```
https://pub.dev/packages/webview_flutter
